services:
  todo-front-dev:
    image: todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-front-dev
