services:
  todo-front-dev:
    image: todo-front-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8080/api/
    depends_on:
      - todo-back-dev
    expose:
      - 5173
    container_name: todo-front-dev

  todo-back-dev:
    image: todo-back-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    expose:
      - 3000
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - redis
      - mongo
    container_name: todo-back-dev

  mongo:
    image: mongo
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    expose:
      - 6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse_proxy
    depends_on:
      - todo-front-dev
      - todo-back-dev
