services:
  frontend:
    image: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8000/api/
    expose:
      - 80
    depends_on:
      - backend

  backend:
    image: blog-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverse_proxy
    depends_on:
      - frontend
      - backend
